services:
  - type: web
    name: m-chavda-security-world
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MCSW_SECRET
        generateValue: true
